services:
  loja_web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - gameshop_db

  gameshop_db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gameshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
