# Generated by Django 5.1.6 on 2025-02-18 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('bio', models.CharField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_producer', to='gameshop.gameproducer')),
            ],
        ),
    ]
