# Generated by Django 5.1.6 on 2025-02-18 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0002_games'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
