# Generated by Django 5.1.6 on 2025-02-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0003_rename_games_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='games/'),
        ),
    ]
